---
# Tasks for create_user(s) roles
- name: Add user(s) to the system
  user:
    name: "{{ user_name }}"
    comment: "{{ user_comment | default(user_created_by_ansible) }}"
    group: "{{ user_primary_group }}"
    groups: "{{ user_groups | {{ user_primary_group }} }}"
    shell: "{{ user_shell | default('/bin/bash') }}"
    state: "{{ user_state }}"
