---
# Tasks for create_user(s) roles
- name: Add user(s) to the system
  user:
    name: "{{ item.user_name }}"
    comment: "{{ item.user_comment | default(user_created_by_ansible) }}"
    group: "{{ item.user_primary_group }}"
    groups: "{{ item.user_groups | default(user_primary_group) }}"
    shell: "{{ item.user_shell | default('/bin/bash', true) }}"
    state: "{{ item.user_state | default('present', true)}}"
  with_items: "{{ users }}"
